### ISSUE TITLE
Game Crash Upon Playing A New World

### ISSUE THREAD

**Issue by Cropsis** [miyo6032/bosses-of-mass-destruction#10]
i wanted to play this mod cause of the bosses (obviously) but every time i've tried to open a new world and play it the game would crash bringing me back to the launcher, anyone know how to fix this?
[crash-2021-05-04_22.04.35-client.txt](https://github.com/miyo6032/bosses-of-mass-destruction/files/6487572/crash-2021-05-04_22.04.35-client.txt)

**Comment by miyo6032** [comment]
Seems like you don't have geckolib installed - double check the installation instructions
