### ISSUE TITLE
[1.18.2] Nether Gauntlet Incompatible with Forgotten Graves 

### ISSUE THREAD

**Issue by ConqAra** [miyo6032/bosses-of-mass-destruction#106]
Nether gauntlet boss will break graves that aren't suppose to break. The graves from [Forgotten Graves](https://github.com/ginsm/forgotten-graves/) have a blast resistance of 3600000 (same as bedrock), but the gauntlet's explosions and attacks still broke the gravestone when killing the player and having their gravestone spawn. Just seems frustrating when trying to fight the boss and losing everything. Is this suppose to happen?

**Comment by miyo6032** [comment]
it should break whatever blocks the wither can - would have to add it to wither immune block tags i believe
