### ISSUE TITLE
Bosses can't attack mobs

### ISSUE THREAD

**Issue by NEFFLEAFF** [miyo6032/bosses-of-mass-destruction#108]
Only the gauntlet and obsidilith can correctly target them. On the other hand, the reamining two only play their animations and don't actually deal damage or even attack.
I must say this can be a big issue as cheesing with pets or golems is too easy

**Comment by NEFFLEAFF** [comment]
Oh, I'm talking about a bit of extra modded stuff. Void blossom is dying to snow golems due to a mod letting them deal damage.
And the lich, yeah that one was pretty much forced.

**Comment by miyo6032** [comment]
so people are spawning snow golems around it? snow golems will die pretty quickly by certain attacks when the void blossom is attacking the player normally

**Comment by NEFFLEAFF** [comment]
And that's where the issue comes: Void blossom focused on the snow golems because they hit it first.

**Comment by NEFFLEAFF** [comment]
An easier way to realize its easy to cheat: use an iron golem and let him hit void blossom first, then use a lead to keep him at safe from the thorns. This way the boss stays focused in the golem, unable to attack, while player can easily kill it with a bow.

**Comment by miyo6032** [comment]
Ok i revisited, and the bosses should never actually focus on anything besides the player - this is because the bosses take very little damage when they are idle to make sure that they cannot be destroyed by the environment. if they are targeting entities, there is some other mod at play that is affecting this

**Comment by NEFFLEAFF** [comment]
Out of curiosity, why is the gauntlet capable of performing attacks against mobs but the other two aren't?

**Comment by miyo6032** [comment]
all bosses share the same targeting, with is ONLY the player

**Comment by NEFFLEAFF** [comment]
Ok so this is not a bug. Guess this stays as a suggestion.
