### ISSUE TITLE
Crash on latest fabric loader [Fabric 0.15.0/1.19.2]

### ISSUE THREAD

**Issue by pokesmells** [miyo6032/bosses-of-mass-destruction#109]
[crash-2023-11-29_16.07.47-client.txt](https://github.com/miyo6032/bosses-of-mass-destruction/files/13505950/crash-2023-11-29_16.07.47-client.txt)

Crashes on start-up.

**Comment by miyo6032** [comment]
uploaded a fix

**Comment by MeatVegetalbe** [comment]
Same here, I removed your mod and the rest worked completely fine afterwards.
[crash-2023-11-30_19.02.33-client.txt](https://github.com/miyo6032/bosses-of-mass-destruction/files/13517302/crash-2023-11-30_19.02.33-client.txt)

**Comment by miyo6032** [comment]
i uploaded a fix for the 1.20.1 version

**Comment by Joulanh** [comment]
Could you upload the fix on modrinth please?
