### ISSUE TITLE
Exception in server tick loop  BOMD-1.7.4-1.20.1.jar  Fabric 0.15.3 

### ISSUE THREAD

**Issue by gamerpotion** [miyo6032/bosses-of-mass-destruction#115]
Hi, not sure if its BOMD but keep getting our server crashing with - https://pastebin.com/J3errZEr

This is for the latest version of DarkRPG modpack with all mods updated.

**Comment by miyo6032** [comment]
it is due to https://github.com/Snownee/Jade calling something it shouldn't but i will see if it can be fixed from my side

**Comment by miyo6032** [comment]
1.7.5 should probably fix this

**Comment by gamerpotion** [comment]
> 1.7.5 should probably fix this

Hi, we have switched to using WTHIT and had removed BOMD.  If we re-add, will this issue be resolved with WTHIT as well?

**Comment by miyo6032** [comment]
i am not sure what WTHIT is but if there is an issue after trying send me a log and i will try to fix it

**Comment by gamerpotion** [comment]
Ah yeah, its similar to Jade - https://modrinth.com/mod/wthit
but since it uses similar format of displaying the information just wondered if it would happen with that. Will try and see if can replicate it but it was quite random on the official servers when it was happening
