### ISSUE TITLE
Crash - Prominence II / The Bumblezone

### ISSUE THREAD

**Issue by goldern** [miyo6032/bosses-of-mass-destruction#124]
1. What Minecraft version are you using? (1.19.2, 1.20.1, ...)
1.20.1

2. What launcher did you run Minecraft with? (e.g. CurseForge, ATLauncher, MultiMC, ...)
Prism Launcher 8.3

3. Have you changed the modpack in any way? (e.g. changing mod versions, adding/removing mods)
Added FindMe to help avoiding duplicate item in chests

4. What version of the modpack are you using? (v11, v9, etc)
2.8.3

5. Have you ever gotten past the crash condition without crashing, or does the game always crash?
Always crashing

6. What steps cause the crash?
Entered The Bumblezone dimension, then it always crashes now.

```
java.lang.NoSuchFieldError: pollenParticles
    at net.barribob.boss.block.VoidLilyBlockEntity.<clinit>(VoidLilyBlockEntity.kt:75)
    at net.barribob.boss.block.ModBlocks.voidLilyBlockEntityFactory$lambda$9(ModBlocks.kt:72)
    at net.barribob.boss.block.VoidLilyBlock.method_10123(VoidLilyBlock.kt:23)
    at net.minecraft.class_2818.method_12204(class_2818.java:530)
```

[crash-2024-05-16_09.38.33-server.txt](https://github.com/miyo6032/bosses-of-mass-destruction/files/15336228/crash-2024-05-16_09.38.33-server.txt)

**Comment by TelepathicGrunt** [comment]
Just fyi, update to v2.8.4 of this modpack to fix crash. They updated Bosses of Mass Destruction and the crash stopped.
