### ISSUE TITLE
1.21-BOMD-1.10.0-1.21 Chinesization Fail to take effect

### ISSUE THREAD

**Issue by mcmaidong** [miyo6032/bosses-of-mass-destruction#129]
![image](https://github.com/user-attachments/assets/20170a1f-79bc-45af-88a0-44c19441f1b6)

![image](https://github.com/user-attachments/assets/3ba3723e-2707-47d8-bea3-04d4c328a40b)
Chinesization Fail to take effect

**Comment by miyo6032** [comment]
should be fixed in 1.10.1
