### ISSUE TITLE
Night Lich taking too much CPU

### ISSUE THREAD

**Issue by NyanMaths** [miyo6032/bosses-of-mass-destruction#15]
I don't know if you can, but it would be really cool if this boss could stop making my computer vomiting blood when I summon it. It was just for that, thanks by advance if you can further optimize it !

**Comment by miyo6032** [comment]
The lich should not be doing that. Does that happen when the mod is by itself and dependencies?

**Comment by NyanMaths** [comment]
Yes the problem remains even with only BOMD and its dependencies installed. I tested with the lastest 1.16.5 version and the alpha build for 1.17, both have the same problem : my computer becomes slower (FPS drop, the fan goes crazy...) but nothing crashes. I noticed there is also a little drop with the other bosses, but much lesser than the first one. My computer is really old and slow, maybe it is less noticeable for yours, but mine goes from almost 60 to 20-40 FPS on a superflat world while it is alive.

**Comment by miyo6032** [comment]
May I ask what your specs are in terms of graphics, cpu, and memory allocated? They should all be listed on the f3 menu in Minecraft.

I am unable to replicate any meaningful drop in FPS on my machine with a single lich boss. (What I am seeing on my side is that it takes about 10 liches to drop 10 FPS)

At some point, I may try to spin up a virtual machine with similar specs and see what happens.

**Comment by NyanMaths** [comment]
Yes, it could be a rendering issue, my graphic card is quite old and I already noticed driver issues, so...

CPU : Intel i3 M350 (2.27 GHz, 2 cores, 4 threads, L1 128KB, L2 512KB, L3 3MB)
Graphics : AMD Radeon 6300M HD
RAM : 4 GB DDR3 1067 MHz
