### ISSUE TITLE
Could not execute entrypoint stage 'main' due to errors, provided by 'bosses_of_mass_destruction'!

### ISSUE THREAD

**Issue by Sl1pstr3am** [miyo6032/bosses-of-mass-destruction#16]
Modlist:
Fabric API
Bosses of Mass Destruction
Fabric Language Kotlin

Error:
Game immediately crashes on startup. Crash report is attached.
I have Java 16 installed.
[crash-2021-06-23_14.32.48-client.txt](https://github.com/miyo6032/bosses-of-mass-destruction/files/6704477/crash-2021-06-23_14.32.48-client.txt)

**Comment by Sl1pstr3am** [comment]
So I took a look at older issues, and tried installing Geckolib, but it still crashes. 
Crash report is attached.
[crash-2021-06-23_18.48.45-client.txt](https://github.com/miyo6032/bosses-of-mass-destruction/files/6705394/crash-2021-06-23_18.48.45-client.txt)

**Comment by miyo6032** [comment]
Needs cloth config and cardinal components - add that and see if it works

**Comment by josesobral22005813** [comment]
I added both and it still gives me the same crash at startup.
I attached the crash report
[crash-2021-06-25_19.01.43-client.txt](https://github.com/miyo6032/bosses-of-mass-destruction/files/6718167/crash-2021-06-25_19.01.43-client.txt)

**Comment by Sl1pstr3am** [comment]
> Needs cloth config and cardinal components - add that and see if it works

That worked, thanks! I'd recommend adding both as dependencies in your fabricmod.json for future reference.

**Comment by miyo6032** [comment]
josesobral22005813 - add geckolib.
