### ISSUE TITLE
cant load  already made world 

### ISSUE THREAD

**Issue by TheNimbleNinja** [miyo6032/bosses-of-mass-destruction#18]
A crash is most likely going to happen right after this report!
 It seems bosses_of_mass_destruction:lich_tower | bosses_of_mass_destruction:lich_tower is the cause because it is not added 
 to the FlatChunkGeneratorConfig.STRUCTURE_FEATURE map. Please let the mod owner 
 of that structure know about this crash. That way they can add their structure 
 to that map since someone is trying to spawn it in a flat/custom dimension. 

this was in the log

**Comment by miyo6032** [comment]
Thanks for reporting, I will investigate further

**Comment by miyo6032** [comment]
This should be fixed in version 1.2.2 - any existing superflat worlds won't be fixed. You will have to manually delete the structures from the level.dat if you really need it.
