### ISSUE TITLE
Crash with Mob Parkour

### ISSUE THREAD

**Issue by PalgamingHD** [miyo6032/bosses-of-mass-destruction#2]
I don't know if this is something you can fix on your side or theirs but crashed when you have both: 

https://pastebin.com/AwX0JXmR

**Comment by miyo6032** [comment]
Can you list the versions you are using for both?

**Comment by PalgamingHD** [comment]
Latest for both:

BOMB 1.0

MAP 0.2.2

Minecraft 1.16.4

Fabric API 0.32.5

**Comment by PalgamingHD** [comment]
Spoke too soon, 0.2.2 doesn't crash
