### ISSUE TITLE
Pickaxes break many blocks at the same speed as fists.

### ISSUE THREAD

**Issue by jesuschrist4202** [miyo6032/bosses-of-mass-destruction#25]
Obsidian Runes, Ancient Carved Blackston, Table of elevation, Staff of suppression, Blast amplifier, and probably some other blocks do not break faster when using a pickaxe compared to using your fists.

I have all dependencies, fabric 1.17.1, and the latest version of mod.

Last boss is basically immortal unless you use cheap tricks because of this and the nether boss takes 4+ minutes to summon.

**Comment by miyo6032** [comment]
I cannot replicate - can you tell me what all of your versions are specifically please?

**Comment by jesuschrist4202** [comment]
Caused by betternether, removing that mod fixes it.
Aeternium from betterend can mine it just fine, but netherite with efficiency 5 is as slow as fists with betternether.

My mods list with betternether:
![Screenshot_1](https://user-images.githubusercontent.com/87919245/128797904-a61e2725-5719-46d3-91bf-88070e0209cd.png)

video: https://anonfiles.com/pfN9qfB5u5/Untitled_mp4

**Comment by miyo6032** [comment]
Very interesting - I will investigate further at some point thanks for reporting

**Comment by miyo6032** [comment]
Unable to replicate this is my current modlist I am using:
  [✔️] bclib-0.2.4
  [✔️] better-end-0.10.5-pre
  [❌] better-end-0.11.0-pre.jar (disabled)
  [✔️] better-nether-5.1.3
  [✔️] BOMD-1.2.3-1.17.1
  [✔️] Cardinal-Components-API-3.1.1
  [✔️] cloth-config-5.0.34-fabric
  [❌] directional-tnt-1.17-0.1.jar (disabled)
  [✔️] fabric-api-0.37.2+1.17
  [✔️] fabric-language-kotlin-1.5.0+kotlin.1.4.31
  [✔️] geckolib-fabric-1.17-3.0.11
  [❌] geckolib-fabric-1.17-3.0.5.jar (disabled)
  [❌] mobs-attempt-parkour-0.2.3-1.17-pre1.jar (disabled)
  [✔️] modmenu-2.0.0-beta.7
  [❌] Wither-Totems-Mod-0.3.3-1.17-pre1.jar (disabled)
  [❌] worldedit-fabric-mc1.17-7.2.6-SNAPSHOT-dist.jar (disabled)

Was able to break blackstone and rune with netherite pickaxe.
I wonder if there is some sort of integration with betternether that I am not aware of. Are there any mods that introduce new tools. Also do you have any resource/datapacks?

**Comment by jesuschrist4202** [comment]
It happens when I put
`"cincinnasite_pickaxe_diamond[def: true]": false,`
in items.json in betternether config

very strange not sure why it affects vanilla items, I disabled all cincinnasite diamond tools cause they were too overpowered and made netherite useless
