### ISSUE TITLE
game crashing when i open 1.16.5

### ISSUE THREAD

**Issue by kur0lwastaken** [miyo6032/bosses-of-mass-destruction#27]
hi, my game keep crashing when i try to open this mod on 1.16.5.
I already have all required mods, do i need an old version of geckolib? im using the 3.0.47 version (geckolib), could you please help me?

**Comment by miyo6032** [comment]
I don't know for sure because I haven't seen the crashlog, but it is likely you need an older version of geckolib

**Comment by kur0lwastaken** [comment]
> I don't know for sure because I haven't seen the crashlog, but it is likely you need an older version of geckolib

It doesnt show any crashlog, it just crash instantly. And do u know the old version u talking aboout?

**Comment by miyo6032** [comment]
A new 1.16.5 version will be up soon and should fix this issue

**Comment by kur0lwastaken** [comment]
> A new 1.16.5 version will be up soon and should fix this issue

Ok, thanks!
