### ISSUE TITLE
Subtitles are not formatted correctly - see screenshot as I can't explain.

### ISSUE THREAD

**Issue by NaZzAtAzEr** [miyo6032/bosses-of-mass-destruction#3]
![image](https://user-images.githubusercontent.com/22560082/114626961-5a67eb80-9cac-11eb-9349-563747769170.png)

**Comment by miyo6032** [comment]
Noted. I can fix this probably this weekend.

**Comment by miyo6032** [comment]
Fixed in 1.0.1
