### ISSUE TITLE
Crash on loading with latest Geckolib on 1.17.1

### ISSUE THREAD

**Issue by Muffintiem** [miyo6032/bosses-of-mass-destruction#33]
The 1.17.1 version is not compatible with Geckolib 3.0.13 and staying on an earlier version of Geckolib is not an option because that breaks other mods that depend on the newest version of Geckolib.

**Comment by miyo6032** [comment]
I am seeing no issues with 3.0.13 - can you specify what the issue is or post a crashlog. Thanks

**Comment by Muffintiem** [comment]
https://pastebin.com/BEpskUYz

This same set of errors kept repeating.

**Comment by miyo6032** [comment]
Can you post your modlist. At first glance, the error does not seem to be due to a geckolib class

**Comment by Muffintiem** [comment]
To help narrow the problem down, I created a separate clean instance with:
BOMD 1.2.1
Cardinal Components API 3.0.0
Cloth config 5.0.37
Fabric api 0.39.2
Fabric language kotlin 1.6.4 + kotlin 1.5.30
Geckolib fabric 1.17 - 3.0.13

It also happens with every instance of Geckolib past 3.0.10 including the new one that dropped today.
