### ISSUE TITLE
Invalid Player Data Error

### ISSUE THREAD

**Issue by Foufou10** [miyo6032/bosses-of-mass-destruction#40]
Since I updated Cardianal Components in my mods list, BOMD doesn't want to work anymore. Each time I join a world, an error appears in my console and I have the message "Invalid Player Data", the game kicking me back to the menu.

Here's the crash report : https://pastebin.com/1jPgB1md

**Comment by miyo6032** [comment]
You are using 3.1.1? Can you show me your modlist? My first guess is that you downloaded a piece of the mod, but not the full one
