### ISSUE TITLE
Crash.

### ISSUE THREAD

**Issue by MagmaBro123** [miyo6032/bosses-of-mass-destruction#43]
Modlist in report.

https://pastebin.com/dvczrz22

**Comment by miyo6032** [comment]
U are missing geckolib fabric and cardinal components mods I believe. Check installation spoiler on mod page.

**Comment by MagmaBro123** [comment]
Added those. Same crash.

**Comment by miyo6032** [comment]
Show me the crashlog then I can help

**Comment by MagmaBro123** [comment]
See the above crash report. Its the same thing.

**Comment by miyo6032** [comment]
If it is saying geckolib is still missing, then the wrong version of geckolib is probably there. What is the name of the geckolib jar you are using?

**Comment by MagmaBro123** [comment]
I used the latest version of it that was on Curse.
