### ISSUE TITLE
Game crashes when i start it 

### ISSUE THREAD

**Issue by GruselGeist** [miyo6032/bosses-of-mass-destruction#46]
When I launch the Game this appears 
ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
Install fabric-language-kotlin, any version.
Unmet dependency listing:
Mod 'Bosses of Mass Destruction (Beta)' (bosses_of_mass_destruction) 1.2.3-1.16.5 requires any version of fabric-language-kotlin, which is missing!
<html>at net.fabricmc.loader.impl.discovery.ModResolver.findCompatibleSet(ModResolver.java:159)<br/>at net.fabricmc.loader.impl.discovery.ModResolver.resolve(ModResolver.java:45)<br/>at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:224)<br/>at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:187)<br/>at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142)<br/>at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)<br/>at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)</html>

**Comment by miyo6032** [comment]
I guess have you tried what it says to do:

A potential solution has been determined:
Install fabric-language-kotlin, any version.

**Comment by GruselGeist** [comment]
it worked!
