### ISSUE TITLE
Soul Stars wont work. 

### ISSUE THREAD

**Issue by Sh1kiS** [miyo6032/bosses-of-mass-destruction#50]
Playing on 1.18.1 and soul stars wont work on my world and even in creative i dont know why.

**Comment by miyo6032** [comment]
There may be a conflict with yung's API - not totally sure though - are there other mods being used

**Comment by Sh1kiS** [comment]
> 

I use this modpack called "Medieval Minecraft" I watched youtubers and it works for them

**Comment by miyo6032** [comment]
can you perform this command: /locate bosses_of_mass_destruction:lich_tower

**Comment by miyo6032** [comment]
Actually, there was a critical issue with yung's API. I would update that to the newest version - seems like it caused modded structures to not spawn. :(

**Comment by Sh1kiS** [comment]
> /locate bosses_of_mass_destruction:lich_tower

Tried it and it says "Could not find that stucture nearby"

**Comment by miyo6032** [comment]
Yea, I think none of the structures spawned because of yung's API - I cannot help with that unfortunately. You can either recreate the world, or go far to generate new chunks
