### ISSUE TITLE
Game crashes when night litch fires comet

### ISSUE THREAD

**Issue by Voorne** [miyo6032/bosses-of-mass-destruction#51]
Started the night litch fight and crashed after a few sec. Looking through the crash report it has something to do with "bosses_of_mass_destruction:comet"

Here is the crash report:
[crash-2022-02-06_10.14.26-client.txt](https://github.com/miyo6032/bosses-of-mass-destruction/files/8009840/crash-2022-02-06_10.14.26-client.txt)

Installed mods:
BOMD-1.2.3-1.16.5.jar
Cardinal-Components-API-2.8.3.jar
cloth-config-4.13.49-fabric.jar
fabric-api-0.42.0+1.16.jar
fabric-language-kotlin-1.7.0+kotlin.1.6.0.jar
geckolib-fabric-1.16.5-3.0.67.jar
lazydfu-0.1.2.jar
lithium-fabric-mc1.16.5-0.6.6.jar
phosphor-fabric-mc1.16.2-0.8.0.jar
reeses_sodium_options-mc1.16.5-1.4.0.jar
sodium-extra-mc1.16.5-0.3.9.jar
sodium-fabric-mc1.16.5-0.2.0+build.4.jar

**Comment by miyo6032** [comment]
For now use an earlier version of geckolib - that library had a recent update the broke things

**Comment by itsdinkd** [comment]
Hi, AQM2 Creator here. 

Any ETA on how long until an update to work with latest geckolib? that isn't an option for my modpack right now as too many mods updated to fix the geckolib issue, too much reversion would need to happen.

**Comment by miyo6032** [comment]
As it so happens, I had time to push out 1.2.4 - that should fix this

**Comment by Eidigii** [comment]
Any plans to build 1.18 version with this fix?
