### ISSUE TITLE
Game crashes when loading a world

### ISSUE THREAD

**Issue by Voorne** [miyo6032/bosses-of-mass-destruction#52]
I tried to create a new world, but it crashes a second after I load in.
[crash-2022-02-08_15.05.08-server.txt](https://github.com/miyo6032/bosses-of-mass-destruction/files/8024421/crash-2022-02-08_15.05.08-server.txt)

**Comment by miyo6032** [comment]
you seem to be missing cardinal components

**Comment by Voorne** [comment]
Oh it didn't automatically install cardinal components.
