### ISSUE TITLE
Spooky Log Warnings

### ISSUE THREAD

**Issue by greensad** [miyo6032/bosses-of-mass-destruction#53]
**Getting these warning in log:**

[Server thread/WARN]: Couldn't create template entity of bosses_of_mass_destruction:obsidilith (class net.minecraft.class_1297)... Defaulting to empty
[Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "dev.onyxstudios.cca._generated_.GeneratedComponentContainer.get$bosses_of_mass_destruction$event_scheduler()" because "<parameter1>" is null
[Server thread/WARN]: Couldn't create template entity of bosses_of_mass_destruction:gauntlet (class net.minecraft.class_1297)... Defaulting to empty
[Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "dev.onyxstudios.cca._generated_.GeneratedComponentContainer.get$bosses_of_mass_destruction$event_scheduler()" because "<parameter1>" is null

**Full Log:** https://paste.ee/p/0ZBus

**Comment by miyo6032** [comment]
Thank you for reporting - was this just at server startup?

**Comment by greensad** [comment]
> 

It was when launching Minecraft through MultiMC, I didn't launch a server but perhaps a mod I'm using has some server properties?
