### ISSUE TITLE
Crashing when fighting the Lich

### ISSUE THREAD

**Issue by KiwiParis** [miyo6032/bosses-of-mass-destruction#55]
Hi! I've recently added this mod and it's dependencies (Minus Mod Menu, I saw that it was optional but could this be what is causing the issue?)

To give a short summary, when me and a friend try to fight the Lich, we always seem too crash when we get close. The crash report is as follows:

[crash-2022-03-01_17.51.02-client.txt](https://github.com/miyo6032/bosses-of-mass-destruction/files/8158840/crash-2022-03-01_17.51.02-client.txt)

**Comment by miyo6032** [comment]
I believe you can just update the mod to 1.3.4
