### ISSUE TITLE
Suggestion: Night Lich summoning item

### ISSUE THREAD

**Issue by PalgamingHD** [miyo6032/bosses-of-mass-destruction#6]
A one time use item, that can summon the night lich, maybe cartable, but only is useable once the player has enough undead mob kills, this would be super helpful with people who are underprepared.

**Comment by miyo6032** [comment]
Yeah, I'm starting to understand that there are some problems with the current way Lich enters the world.

**Comment by bulletbillking** [comment]
you can add a Night Lich staff that will use all of your attacks.

**Comment by bulletbillking** [comment]
you can add a Night Lich staff that will use all of his attacks.
