### ISSUE TITLE
Oh The Biomes You'll Go and Terrestria compatability

### ISSUE THREAD

**Issue by TheSkeletonAppears** [miyo6032/bosses-of-mass-destruction#61]
boss structures like blossom are not spawning and the lich only spawns in ice spikes which is about 50k blocks away from spawn 
TLDR: bosses spawn really far and are annoying to find

**Comment by miyo6032** [comment]
Can you replicate this situation consistently? I installed both of them and I am not seeing the issue occurring

**Comment by TheSkeletonAppears** [comment]
yes, yes I did I opened 5 new worlds with /locate command and found the lich like 20k - 50k blocks away (blossom never spawned)

**Comment by miyo6032** [comment]
This is the mod list i am using is there something different you used
  [✔️] BOMD-1.3.7-1.18.2
  [✔️] cardinal-components-api-4.1.4
  [✔️] cloth-config-6.2.57-fabric
  [✔️] DimensionalDoors-4.0.4-1.18.2
  [✔️] fabric-api-0.47.6+1.18.2
  [✔️] fabric-language-kotlin-1.7.2+kotlin.1.6.20
  [✔️] geckolib-fabric-1.18-3.0.35
  [✔️] Oh_The_Biomes_You'll_Go-fabric-1.18.2-1.4-RC-1
  [✔️] TerraBlender-fabric-1.18.2-1.1.0.91
  [✔️] Terralith_v2.2.1a
