### ISSUE TITLE
1.18.2: generationEnabled config option does nothing

### ISSUE THREAD

**Issue by woalk** [miyo6032/bosses-of-mass-destruction#63]
In the 1.18.2 version (mod version 1.3.7 from CurseForge), the config options `generationEnabled` of all four boss structures does nothing. All structures still generate.

It seems like the `if` statements checking for `generationEnabled` were removed from `ModStructures.kt` in a59f76fa3fb5404587e20a72e6a8311f5de692ad (_Update everything to 1.18.2 except structures_) and never brought back in 8ca99d3a33e43b11897760b22c6aeeb1f3dbc9fa (_Update structures 1.18.2 except modded biomes_).

**Comment by miyo6032** [comment]
Ah yes that seems to be the case. I will see if i can put them back in - but probably in 1.19 i will remove the option entirely because with 1.18.2+ the same thing can be achieved by adjusting the datapack for it

**Comment by woalk** [comment]
Oh, that is possible using datapacks? How would one do that?

Would be great to have a short info in a README about that if that way is supposed to replace that option.

Context: I really want to use the elements from this mod on a roleplay server, so I want to be able to control when players can find the structures, i.e. don't automatically generate them.

**Comment by miyo6032** [comment]
I would recommend learning about structures a bit. Here is a guide: https://misode.github.io/guides/adding-custom-structures/
But basically I think the easiest way is to change configured structure feature's biome collection to be empty. E.g. making data/bosses_of_mass_destruction/tags/worldgen/biome/collections/cold.json empty would make the lich one not generate.

You can basically create entire structures and remove them using only datapacks now

**Comment by woalk** [comment]
Oh wow, thank you very much!

I didn't realise data packs got even more powerful again, this will probably be very helpful in general for my project.

I guess you can close this issue then once you've decided what to do with the `generationEnabled` setting.

**Comment by miyo6032** [comment]
Did eventually fix this on 1.18 and 1.19 wasn't super hard to do
