### ISSUE TITLE
Deep Dark can spread to void blossom structure

### ISSUE THREAD

**Issue by Treetrain1** [miyo6032/bosses-of-mass-destruction#67]
Sculk from Deep Dark biomes can spread into and cover the void blossom structures in sculk.

Another issue in this image is that mob spawners that spawn in void blossom structures leave floating chests and spawners
![image](https://user-images.githubusercontent.com/39657565/173193011-8575b586-723c-4f43-b954-d1b7ca57abbb.png)

**Comment by Treetrain1** [comment]
This can allow players to spawn wardens that may start attacking the void blossom, allowing for an easy kill.

**Comment by miyo6032** [comment]
Sculk issue should be fixed in 1.4.1. The floating mob spawners are probably from a dungeon spawning on top... it is probably not going to happen often enough to need a fix, but let me know if it becomes a major problem
