### ISSUE TITLE
BUG 1.19 Fabric Void Blossom loot table is broken

### ISSUE THREAD

**Issue by MaliciousZoroark** [miyo6032/bosses-of-mass-destruction#68]
Killing it AND the /loot command drops nothing.

**Comment by miyo6032** [comment]
How are you killing it - the loot table requires the player to deal the damage, thus /loot will not drop and /kill will not either

**Comment by MaliciousZoroark** [comment]
Yes, killing it using player damage drops no loot.

**Comment by miyo6032** [comment]
How exactly are you killing it - I've tested with bow, and with melee damage and it seems to work fine
