### ISSUE TITLE
Night Lich disseappered after i spawned it

### ISSUE THREAD

**Issue by fanaco** [miyo6032/bosses-of-mass-destruction#69]
Me and a friend were playing on my better minecraft survival (v12) on 1.18.2 and we makes the lich spawn at its tower but after get spawn it ran away and we were not fast enough to hit him any time... the real issue is that the soul star goes at the same ice tower than before and the 4 altar dispawned after we spawned the boss 

please consider help me 
my discord if u wanna sned me a fix fvnvco#2860

**Comment by miyo6032** [comment]
craft the brimstone nectar item to repair the structure
