### ISSUE TITLE
suggestion for the night lich

### ISSUE THREAD

**Issue by SpinnyBoiii** [miyo6032/bosses-of-mass-destruction#7]
spawning:
maybe spawn an arena of some kind instead of infinite night? i cant exactly imagine people hundreds of chunks away in a multiplayer server enjoying a sudden nighttime that doesnt stop because one person fails to kill it(either by accidental summon or just failing to kill it in general)

undead kill counter:
maybe remain visible after hitting a checkpoint? was testing and noticed that it disappeared after a short while once it showed the value

id already seen a different suggestion about it being with an item once the required amount of kills was enough, the undead kill counter being shown only when holding such an item would also do well for keeping track imo

**Comment by miyo6032** [comment]
Yeah, the nighttime mechanic may be problematic for larger servers. If needed, it is configurable.

I see problems with a boss bar or any UI to always be shown just for a boss. I think it would make the UI of the game noisy. In any case, I'm thinking of changing how the boss appears. Namely, I think I'll use a rare generated structure. It also allows for the replayability of the boss. What do you think about that?

**Comment by SpinnyBoiii** [comment]
a rare generated structure would be consistent with the other bosses.
seeing as the boss spawns undead, maybe have this structure be underground rather than aboveground?
that way people cant just cheese the fight by breaking just the structure's ceiling(unless its made out of an unbreakable block) to kill off any undead spawns.

**Comment by miyo6032** [comment]
I think the underground idea would be good, except that the lich needs quite a bit of space to properly move. I'll think about it. Thanks for the suggestions!

**Comment by bulletbillking** [comment]
developer, please add the Night Lich staff
