### ISSUE TITLE
Significant FPS Drops when encountering Lich/Void Lily

### ISSUE THREAD

**Issue by AppelCyder** [miyo6032/bosses-of-mass-destruction#70]
![image](https://user-images.githubusercontent.com/91849511/175207983-de1a8d8b-677c-4f0b-a5ae-ea474dcc756e.png)

Hello, I have been encountering a newly developed issue regarding the Bosses. Upon rendering the VOid Lily and or Night Lich. My FPS tanks to sub 20 FPS. I have tried many solutions but haven't found one specific enough to remedy it. So I would hope futher insight can be provided.

Here is the Modlist I am currently using along with my current Specs:

	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 729597016 bytes (695 MiB) / 2097152000 bytes (2000 MiB) up to 12046041088 bytes (11488 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 5800H with Radeon Graphics         
	Identifier: AuthenticAMD Family 25 Model 80 Stepping 0
	Microarchitecture: unknown
	Frequency (GHz): 3.19
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: AMD Radeon(TM) Graphics
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 512.00
	Graphics card #0 deviceId: 0x1638
	Graphics card #0 versionInfo: DriverVersion=30.0.13014.7002
	Graphics card #1 name: NVIDIA GeForce RTX 3050 Ti Laptop GPU
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 4095.00
	Graphics card #1 deviceId: 0x25a0
	Graphics card #1 versionInfo: DriverVersion=27.21.14.6685
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 37224.25
	Virtual memory used (MB): 17936.08
	Swap memory total (MB): 5120.00
	Swap memory used (MB): 10.72

	- additionaladditions 4.0.5
	- additionalentityattributes 1.0.0+1.18.2 via apoli
	- advancementplaques 1.4.4
	- allay 4.0.0
	- alloy_forgery 2.0.13+1.18
	- apoli 2.3.3 via origins
	- appleskin 2.4.0+mc1.18.2
	- architectury 4.5.75
	- bclib 1.4.7
	- betterend 1.1.1
	- betterf3 1.2.5
	- betternether 6.1.2
	- betterthirdperson 1.8.1
	- blue_endless_jankson 1.2.1 via jankson
	- blur 2.4.1
	- bookshelf 13.2.21
	- bosses_of_mass_destruction 1.3.6-1.18.2
	- byg 1.4
	- caffeineconfig 1.1.0 via sodium-extra
	- calio 1.5.1 via apoli
	- campanion 3.0.3
	- cardinal-components 4.1.4
	- cardinal-components-base 4.1.4 via cardinal-components
	- cardinal-components-block 4.1.4 via cardinal-components
	- cardinal-components-chunk 4.1.4 via cardinal-components
	- cardinal-components-entity 4.1.4 via cardinal-components
	- cardinal-components-item 4.1.4 via cardinal-components
	- cardinal-components-level 4.1.4 via cardinal-components
	- cardinal-components-scoreboard 4.1.4 via cardinal-components
	- cardinal-components-world 4.1.4 via cardinal-components
	- chat_heads 0.6.0
	- chipped 1.2
	- cloth-basic-math 0.6.1 via cloth-config
	- cloth-config 6.2.62
	- com_electronwill_night-config_core 3.6.4 via terrablender
	- com_electronwill_night-config_toml 3.6.4 via terrablender
	- com_eliotlash_mclib_mclib 18 via geckolib3
	- com_eliotlash_molang_molang 18 via geckolib3
	- com_github_llamalad7_mixinextras 0.0.10 via porting_lib
	- com_google_code_findbugs_jsr305 3.0.2 via create
	- continuity 2.0.0+1.18.2
	- controlling 9.0+19
	- crawl 0.10.6
	- create mc1.18.2_v0.4.1+631
	- createaddition ${version}
	- createplus 1.0
	- dripstone_fluid_lib 1.2.0 via milk
	- dynamiccrosshair 3.0+1.18.2
	- dynamiccrosshaircompat 1.0+1.18.2
	- ecologics 1.5.4
	- entityculling 1.5.1
	- extended_armor_bars 1.2.1
	- extraorigins 1.18-11
	- fabric 0.56.1+1.18.2
	- fabric-api-base 0.4.4+d7c144a860 via fabric
	- fabric-api-lookup-api-v1 1.6.2+2373a54560 via fabric
	- fabric-biome-api-v1 8.0.5+22138a0260 via fabric
	- fabric-blockrenderlayer-v1 1.1.12+3ac43d9560 via fabric
	- fabric-command-api-v1 1.1.9+d7c144a860 via fabric
	- fabric-commands-v0 0.2.8+b4f4f6cd60 via fabric
	- fabric-containers-v0 0.1.22+d7c144a860 via fabric
	- fabric-content-registries-v0 3.1.1+c85f2e3860 via fabric
	- fabric-convention-tags-v1 1.0.1+474e4f7960 via fabric
	- fabric-crash-report-info-v1 0.2.1+ee261a3e60 via fabric
	- fabric-data-generation-api-v1 3.0.0+9fcb91d260 via fabric
	- fabric-dimensions-v1 2.1.19+ffb2c71e60 via fabric
	- fabric-entity-events-v1 1.4.8+d7c144a860 via fabric
	- fabric-events-interaction-v0 0.4.19+d7c144a860 via fabric
	- fabric-events-lifecycle-v0 0.2.18+d7c144a860 via fabric
	- fabric-game-rule-api-v1 1.0.13+d7c144a860 via fabric
	- fabric-item-api-v1 1.5.1+6c4e5d0960 via fabric
	- fabric-item-groups-v0 0.3.14+91896a4960 via fabric
	- fabric-key-binding-api-v1 1.0.12+54e5b2ec60 via fabric
	- fabric-keybindings-v0 0.2.10+b4f4f6cd60 via fabric
	- fabric-language-kotlin 1.8.0+kotlin.1.7.0
	- fabric-lifecycle-events-v1 2.1.0+cc71601c60 via fabric
	- fabric-loot-api-v2 1.0.1+e747827960 via fabric
	- fabric-loot-tables-v1 1.1.1+e747827960 via fabric
	- fabric-mining-level-api-v1 2.1.4+cc71601c60 via fabric
	- fabric-models-v0 0.3.6+d7c144a860 via fabric
	- fabric-networking-api-v1 1.0.22+e6b169eb60 via fabric
	- fabric-networking-v0 0.3.9+b4f4f6cd60 via fabric
	- fabric-object-builder-api-v1 2.1.3+032c981d60 via fabric
	- fabric-particles-v1 0.2.12+526dc1ac60 via fabric
	- fabric-registry-sync-v0 0.9.9+0d9ab37260 via fabric
	- fabric-renderer-api-v1 0.4.13+d882b91560 via fabric
	- fabric-renderer-indigo 0.5.1+0ca3bd2b60 via fabric
	- fabric-renderer-registries-v1 3.2.11+b4f4f6cd60 via fabric
	- fabric-rendering-data-attachment-v1 0.3.7+d7c144a860 via fabric
	- fabric-rendering-fluids-v1 2.0.2+54e5b2ec60 via fabric
	- fabric-rendering-v0 1.1.13+b4f4f6cd60 via fabric
	- fabric-rendering-v1 1.10.7+54e5b2ec60 via fabric
	- fabric-resource-conditions-api-v1 2.0.3+91b7aa6660 via fabric
	- fabric-resource-loader-v0 0.5.2+446e059560 via fabric
	- fabric-screen-api-v1 1.0.10+d882b91560 via fabric
	- fabric-screen-handler-api-v1 1.2.1+1f6558e860 via fabric
	- fabric-textures-v0 1.0.12+3ac43d9560 via fabric
	- fabric-transfer-api-v1 1.6.3+f4563ac860 via fabric
	- fabric-transitive-access-wideners-v1 1.1.0+e747827960 via fabric
	- fabricenchantments 0.7.2
	- fabricloader 0.14.8
	- fake-player-api 0.3.0 via create
	- fallingleaves 1.11.1+1.18.2
	- farmersdelight 1.18.2-0.2.1
	- ferritecore 4.2.1
	- fiber 0.23.0-2 via patchouli
	- flywheel 1.18-0.7.0.26 via create
	- forge_tags 2.1 via create
	- forgeconfigapiport 3.2.0 via create
	- friendsandfoes 1.4.5
	- geckolib3 3.0.49
	- genesis 1.18.2-1.0.1
	- iceberg 1.0.38
	- indium 1.0.6+mc1.18.2
	- iris 1.2.5
	- jankson 4.0.0+j1.2.0 via libgui
	- java 17
	- journeymap-api-fabric 1.18.2-1.8-fabric-SNAPSHOT via journeymap-fabric
	- journeymap-fabric 5.8.5
	- kanos_config 0.3.1+1.14.4-1.19 via pehkui
	- lambdabettergrass 1.2.4+1.18
	- lambdynlights 2.1.0+1.17
	- libgui 5.1.0+1.18 via additionaladditions
	- libninepatch 1.1.0 via libgui
	- libraryferret 1.0.3
	- lithium 0.7.10
	- maelstrom_library 1.2.4-1.18.2 via bosses_of_mass_destruction
	- mcwbridges 2.0.3
	- medievalorigins 1.18.x-4.0.2
	- midnightlib 0.3.1 via blur
	- milk 0.3.2 via create
	- minecraft 1.18.2
	- mm 2.3 via crawl
	- moborigins 1.8.1
	- modmenu 3.2.2
	- multipart_entities 1.1.5-1.18.2 via bosses_of_mass_destruction
	- naturescompass 1.18.2-2.0.3-fabric
	- noindium 1.0.1+1.18.2 via create
	- notenoughanimations 1.6.0
	- notenoughcrashes 4.1.6+1.18.2
	- omega-config 1.2.3-1.18.1 via noindium
	- org_anarres_jcpp 1.4.14 via iris
	- org_jetbrains_kotlin_kotlin-reflect 1.7.0 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.7.0 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.7.0 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.7.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_atomicfu-jvm 0.17.3 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.3.3 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.3.3 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.3.3 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.3.3 via fabric-language-kotlin
	- org_joml_joml 1.10.2 via sodium
	- origins 1.4.1
	- origins-classes 1.3.0
	- owo 0.7.2-no-cme+1.18
	- patchouli 1.18.2-71-FABRIC
	- pehkui 3.3.2+1.14.4-1.19
	- phosphor 0.8.1
	- playerabilitylib 1.5.0 via apoli
	- polymorph 0.0.21-1.18.2
	- porting_lib 1.1.317-beta+1.18.2-dev.7ad1f24 via create
	- pride 1.1.0+1.17 via lambdynlights
	- reach-entity-attributes 2.1.1 via campanion
	- reeses-sodium-options 1.4.3+mc1.18.2-build.42
	- registrate-fabric MC1.18.2-1.0.3 via create
	- roughlyenoughitems 8.2.490
	- roughlyenoughresources 2.5.0
	- satin 1.7.0 via blur
	- serialization_hooks 0.2.0+1.18.f5d4aa6 via porting_lib
	- skinlayers 1.4.6-mc1.18.2
	- sodium 0.4.1+build.15
	- sodium-extra 0.4.5+mc1.18.2-build.42
	- spruceui 3.3.3+1.18 via lambdabettergrass
	- team_reborn_energy 2.2.0 via createaddition
	- terrablender 1.1.0.102
	- terrarianslimes 1.2-BETA+1.18
	- yigd 1.3.6

**Comment by notmaroun** [comment]
![image](https://user-images.githubusercontent.com/80657566/175451383-09fc30ef-6485-4e8f-947d-c5b7d1b08057.png)
I can confirm I'm having the same issue with the bosses. Massive FPS drops. I tested this in an instance with only the BMD installed.

**Comment by miyo6032** [comment]
There is something very wrong with geckolib-fabric-1.18-3.0.49.jar - I know 3.0.47 should work perfectly fine for now

**Comment by notmaroun** [comment]
I just reached the same conclusion like 30 minutes ago. I think it's definitely geckolib. Mythic Mounts, which also uses GL lags out super hard on 3.0.4.9 too.

**Comment by AppelCyder** [comment]
I had a feeling it had GeckoLib being responsible. Just wasn't sure if it was specifically that causing it.

**Comment by GameDokter51** [comment]
any known workarounds yet? I am playing on 1.19 and my fps drops to 2 when around the void blossom or night litch. I have a good pc so it shouldn't be this bad.

**Comment by miyo6032** [comment]
Good news geckolib put out a fix for this recently - for 1.18. that would be 3.0.50
