### ISSUE TITLE
This mod isn't a library so it doesn't need the LGPL

### ISSUE THREAD

**Issue by obj-obj** [miyo6032/bosses-of-mass-destruction#71]
LGPL doesn't have a difference compared to normal GPL unless it's being used on a library. Might be a good idea to switch to GPL instead

**Comment by miyo6032** [comment]
From what I know, GPL is incompatible with Minecraft's terms. LGPL is allowed to be used with proprietary software, so it is valid. That is why I use LGPL instead of GPL
