### ISSUE TITLE
Major Frame Drops when fighting lich king on server

### ISSUE THREAD

**Issue by Killercrab432** [miyo6032/bosses-of-mass-destruction#72]
Friend summoned lich king, whenever it was rendered on my screen i experienced major frame drops to about 5-10 fps, logs are attached
[latest.log](https://github.com/miyo6032/bosses-of-mass-destruction/files/8986951/latest.log)

**Comment by Killercrab432** [comment]
Only occurs on the server on single player its perfectly fine

**Comment by miyo6032** [comment]
Upgrade your geckolib to .50 there was a major peformance issue is .49
