### ISSUE TITLE
Void Blossom can sometimes spawn under Ancient Cities

### ISSUE THREAD

**Issue by Treetrain1** [miyo6032/bosses-of-mass-destruction#73]
Sometimes when flying around worlds, I see a void blossom area under ancient cities.

![image](https://user-images.githubusercontent.com/39657565/175861291-bcf71989-04ad-4475-903e-fe6a06f9e884.png)

**Comment by miyo6032** [comment]
what version are you using - it should not generate in deep dark biomes in 1.4.1
