### ISSUE TITLE
No Damage on Nether Gauntlet

### ISSUE THREAD

**Issue by shaye1444** [miyo6032/bosses-of-mass-destruction#74]
1.18

The nether guantlet will randomly stop taking damage and then start to recover all of its heath.

**Comment by miyo6032** [comment]
I need a bit more info on how to replicate before I can help - thanks

**Comment by shaye1444** [comment]
Apologies,

All of fabric 5  v1.3
Using the Botania Crystal Bow
The Crystal Bow has the "Chaos" enchantment
One of the enchantments will cause the bosses from this mod to stop taking damage from all sources

**Comment by miyo6032** [comment]
interesting, i will look at it when i have the chance
