### ISSUE TITLE
1.19 crash

### ISSUE THREAD

**Issue by DogsTongue** [miyo6032/bosses-of-mass-destruction#75]
[crash-2022-07-28_20.26.08-client.txt](https://github.com/miyo6032/bosses-of-mass-destruction/files/9208298/crash-2022-07-28_20.26.08-client.txt)
happened right after "[Render thread/WARN]: Configuration conflict: there is more than one oshi.architecture.properties file on the classpath" if it helps

**Comment by miyo6032** [comment]
Interesting, will take a look when i can

**Comment by miyo6032** [comment]
should be fixed in 1.4.2
