### ISSUE TITLE
Compatible with Dungeon Now Loading.

### ISSUE THREAD

**Issue by sadlyborger** [miyo6032/bosses-of-mass-destruction#78]
When using the mod with DNL(Dungeon Now Loading) some of the particles and monolith(DNL - crafting of items) in DNL is broken. I think it is because of the ticks? But I'm not sure.
To reproduce the same thing, just download them together and locate structure by using /locate structure dnl:plains_castle
This particles will be gone when installed with BOMD and the crafting wont work anymore.
![image](https://user-images.githubusercontent.com/108927538/187009778-5c756c02-06b4-4e74-ae60-100824aab733.png)

**Comment by miyo6032** [comment]
I downloaded it and ran it with bomd on 1.19 - didn't see the same issues the particles and crafting seem to be working - just check the plains one
