### ISSUE TITLE
Better Combat + BOMD - Cannot hit Nether Gauntlet

### ISSUE THREAD

**Issue by ZsoltMolnarrr** [miyo6032/bosses-of-mass-destruction#79]
Minecraft version: 1.19.2
Loader: Fabric
Mod version: BOMD 1.4.2 + Better Combat 1.3.1
https://github.com/ZsoltMolnarrr/BetterCombat

**Use case**
Attacking the Nether Gauntlet with any weapon (such as an Iron Sword).

**Experienced**
- Nether Gauntlet emits some impact sound
- Nether Gauntlet doesn't emit hurt sound
- Nether Gauntlet doesn't take damage

**Expected**
Nether Gauntlet takes damage as it should.

**Additional information**
Better Combat uses a custom client side logic for selecting target based on the collision detection of the weapon swing.
This sends a custom attack request packet to the server, containing a list of entities (hit by the weapon swing)
This packet on the server side is handled by attacking each entity one by one, by the player.

**Comment by lxly9** [comment]
To add to this, it does seem like projectiles don't work for me either, as the boss bar does not move.

**Comment by miyo6032** [comment]
Just to check - the gauntlet's weak point it its eye. It aiming for the eye not working

**Comment by lxly9** [comment]
Yup, when hitting it in the eye with a projectile. It both does not work in survival nor creative. I dont have any mods installed that overhaul projectiles.

**Comment by miyo6032** [comment]
Ok, hitbox logic for gauntlet is using a library so I am not super familiar with it, but I'll look into it

**Comment by Ibaudia** [comment]
Expereincing the same issue with the same setup. Disabling Better Combat fixes the issue.

**Comment by bbharier** [comment]
Experiencing this issue with BOMD 1.4.3 + BetterCombat 1.5.1 on Minecraft 1.19.2

**Comment by miyo6032** [comment]
I can probably make it so that the the entire gauntlet hitbox is attackable not its just eye - only if better combat is loaded. Do we think that would be sufficient for the foreseeable future

**Comment by bbharier** [comment]
That seems like a decent compromise. Would projectiles still only work if they hit the eye?

**Comment by lxly9** [comment]
Hm, weird, while testing recently it worked for me, ill post details later, cant test right now.

**Comment by SplendidAlakey** [comment]
> I can probably make it so that the the entire gauntlet hitbox is attackable not its just eye - only if better combat is loaded. Do we think that would be sufficient for the foreseeable future

Yes, absolutely. Anything is better, than having to disable the boss altogether, while using BetterCombat.

**Comment by ZsoltMolnarrr** [comment]
Hello!
Sorry for the late response on the topic.
@miyo6032 has contacted me with details on the matter.

As far as I can see, I could implement add compatibility for the very specific MultiPartEntity library that BoMD uses.
Unfortunately I my development capacities are fully allocated for the next few weeks, due to an upcoming new release.

Even if I find time to fix this, I am not entirely sure how it should work. Better Combat weapon swing works not by raycasting for target, but instead the shape/trajectory of the weapon swing is geometrically approximated (fancy animations are just sugar coating). While this target selection is also capable of returning which entity is infront, the question is would it be a good user experience having to hard aim a specific part even with slash style attacks?

**Comment by lxly9** [comment]
It works on Better Combat 1.5.0+1.19 and BOMD 1.4.3-1.19.2, the Nether gauntlet can be killed with a bow on these specific versions

**Comment by bbharier** [comment]
> Hello! Sorry for the late response on the topic. @miyo6032 has contacted me with details on the matter.
> 
> As far as I can see, I could implement add compatibility for the very specific MultiPartEntity library that BoMD uses. Unfortunately I my development capacities are fully allocated for the next few weeks, due to an upcoming new release.
> 
> Even if I find time to fix this, I am not entirely sure how it should work. Better Combat weapon swing works not by raycasting for target, but instead the shape/trajectory of the weapon swing is geometrically approximated (fancy animations are just sugar coating). While this target selection is also capable of returning which entity is infront, the question is would it be a good user experience having to hard aim a specific part even with slash style attacks? The idea doesn't really appeal to me. One idea that crossed my mind, maybe these specific weak points should accept damage attempts from stab attacks only? (Better Combat stab attacks are forward reaching box shaped hitboxes, typically used by stab weapons such as spear, trident, etc...)

Without a failure animation, it would be unintuitive why swing attacks passing through the weak point don’t do damage to the boss. As long as the swing passed through the open weak spot, players would expect the attack should at least damage the boss a bit. 

I liked [Ibaudia](https://github.com/Ibaudia)‘s idea above about ranged (and potentially stab attacks) doing more damage than swings, but that may be larger in scope than a simple mod compatibility bandaid.

**Comment by miyo6032** [comment]
@bbharier projectiles will hit everything as well
@Ibaudia the gauntlet difficulty can be adjusted accordingly in configs

**Comment by miyo6032** [comment]
1.4.6 should have this partial fix
