### ISSUE TITLE
SimpleLivingGeoRenderer needs updated with the new Geckolib Changes

### ISSUE THREAD

**Issue by AzureDoom** [miyo6032/bosses-of-mass-destruction#80]
We are in the progress of updating all the renders for support of texture per bone, which is requiring extra code in all renders. As your https://github.com/miyo6032/bosses-of-mass-destruction/blob/1.19/src/main/kotlin/net/barribob/boss/mob/utils/SimpleLivingGeoRenderer.kt is a custom, you will need to add add https://github.com/bernie-g/geckolib/blob/1.19/Fabric/src/main/java/software/bernie/geckolib3/renderers/geo/GeoEntityRenderer.java#L432-L440 to your render for it to work with the latest update (would PR but I know shit about KT so figured it would be easier to add an issue here)

**Comment by miyo6032** [comment]
Appreciate the notice

**Comment by gamerpotion** [comment]
hi, just checking will this be updated?
we had to remove BOMD from our modpack recently but will add it back with the update
thanks
