### ISSUE TITLE
Crash upon spawning Lich Boss in newest version 

### ISSUE THREAD

**Issue by masterschief** [miyo6032/bosses-of-mass-destruction#81]
https://pastebin.com/CPW8d3N9

Was playing on a server with 2 other friends and after we put the stars down into the altar to spawn the Lich we instantly hard crashed. I tried downgraded GeckoLib to see if the new version is what was causing issues to no avail.

**Comment by miyo6032** [comment]
Update this mod to 1.4.3 - geckolib introduced a breaking change
