### ISSUE TITLE
Nether Gaunlet Crash

### ISSUE THREAD

**Issue by DemonMartin** [miyo6032/bosses-of-mass-destruction#82]
Launcher: Curseforge
Modpack: Fabrinaz
Issue: Random Crash in Nether (apparently crash when rendering Nether Gaunlet)
Ver: Fabric, 1.18.2
Error: https://bin.dojnaz.cloud/vayew.yaml

**Comment by miyo6032** [comment]
update to 1.3.9 should fix your issue
