### ISSUE TITLE
great mod！zh_cn.json pls

### ISSUE THREAD

**Issue by DarkCrystalll** [miyo6032/bosses-of-mass-destruction#86]
{
  "entity.bosses_of_mass_destruction.comet": "彗星",
  "entity.bosses_of_mass_destruction.lich": "夜巫妖",
  "entity.bosses_of_mass_destruction.blue_fireball": "蓝色火球",
  "entity.bosses_of_mass_destruction.soul_star": "灵魂之星",
  "entity.bosses_of_mass_destruction.obsidilith" : "黑曜石",
  "entity.bosses_of_mass_destruction.gauntlet" : "下界手套",
  "entity.bosses_of_mass_destruction.void_blossom" : "虚空之花",
  "entity.bosses_of_mass_destruction.spore_ball" : "孢子",
  "entity.bosses_of_mass_destruction.petal_blade" : "花瓣之刃",

  "block.bosses_of_mass_destruction.obsidilith_end_frame" : "黑曜石祭坛",
  "block.bosses_of_mass_destruction.obsidilith_rune" : "黑曜石符文",
  "block.bosses_of_mass_destruction.sealed_blackstone" : "密封黑石砖",
  "block.bosses_of_mass_destruction.gauntlet_blackstone" : "古代雕刻黑石",
  "block.bosses_of_mass_destruction.chiseled_stone_altar" : "凿石祭坛",
  "block.bosses_of_mass_destruction.void_blossom_block" : "虚空之花 Boss Spawner",
  "block.bosses_of_mass_destruction.void_lily" : "虚空百合",
  "block.bosses_of_mass_destruction.void_lily.tooltip" : "花粉会引向哪里？",
  "block.bosses_of_mass_destruction.void_blossom" : "虚空之花",
  "block.bosses_of_mass_destruction.vine_wall" : "荆棘墙",

  "itemGroup.bosses_of_mass_destruction.items" : "大规模毁灭首领",

  "item.bosses_of_mass_destruction.soul_star" : "灵魂之星",
  "item.bosses_of_mass_destruction.soul_star.tooltip" : "它通向哪里？",
  "item.bosses_of_mass_destruction.ancient_anima" : "古代心能",
  "item.bosses_of_mass_destruction.blazing_eye" : "炽热之眼",
  "item.bosses_of_mass_destruction.obsidian_heart" : "黑曜石之心",
  "item.bosses_of_mass_destruction.void_thorn" : "虚空刺",
  "item.bosses_of_mass_destruction.crystal_fruit" : "水晶果实",
  "item.bosses_of_mass_destruction.crystal_fruit.tooltip" : "提供短暂的恢复和抵抗",
  "item.bosses_of_mass_destruction.charged_ender_pearl" : "充电末影珍珠",
  "item.bosses_of_mass_destruction.charged_ender_pearl.tooltip" : "可重复使用并给出简要说明",
  'item.bosses_of_mass_destruction.charged_ender_pearl.tooltip2':'传送后的抵抗力',
  "item.bosses_of_mass_destruction.crafting_material.tooltip" : "制作材料",
  "item.bosses_of_mass_destruction.brimstone_nectar" : "硫磺花蜜",
  "item.bosses_of_mass_destruction.brimstone_nectar.tooltip" : "使用时重置附近的首领建筑",

  "block.bosses_of_mass_destruction.mob_ward" : "镇压法杖",
  "item.bosses_of_mass_destruction.mob_ward.tooltip" : "放置后,生物不会在任何 64 格方向上生成",

  "block.bosses_of_mass_destruction.monolith_block" : "冲击放大器",
  "item.bosses_of_mass_destruction.monolith_block.tooltip_0" : "放置后,任意增加 30% 爆炸威力",
  "item.bosses_of_mass_destruction.monolith_block.tooltip_1" : "64 方块方向。此效果无法叠加",

  "block.bosses_of_mass_destruction.levitation_block" : "高程表",
  "item.bosses_of_mass_destruction.levitation_block.tooltip" : "放置后,在 7x7 列中提供创意飞行",

  "item.bosses_of_mass_destruction.earthdive_spear.tooltip" : "通过固体方块进行短距离传送",
  "item.bosses_of_mass_destruction.earthdive_spear" : "地潜矛",

  "advancements.nether.gauntlet_defeat.title": "穿过手套",
  "advancements.nether.gauntlet_defeat.description" : "击败虚空手套 Boss",

  "advancements.end.obsidilith_defeat.title": "黑曜石湮灭者",
  "advancements.end.obsidilith_defeat.description" : "击败黑曜石首领",

  "advancements.adventure.night_lich_defeat.title": "黑夜征服者",
  "advancements.adventure.night_lich_defeat.description": "击败夜巫妖首领",

  "advancements.adventure.void_blossom_defeat.title": "极端除草",
  "advancements.adventure.void_blossom_defeat.description": "击败虚空之花首领",

  "subtitles.bosses_of_mass_destruction.gauntlet_idle" : "Gauntlet Breathes",
  "subtitles.bosses_of_mass_destruction.gauntlet_hurt" : "Gauntlet Hurts",
  "subtitles.bosses_of_mass_destruction.gauntlet_cast" : "Gauntlet Casts",
  "subtitles.bosses_of_mass_destruction.gauntlet_spin_punch" : "Gauntlet Spins",
  "subtitles.bosses_of_mass_destruction.gauntlet_laser_charge" : "Gauntlet 蓄力",
  "subtitles.bosses_of_mass_destruction.gauntlet_death" : "Gauntlet Dies",
  "subtitles.bosses_of_mass_destruction.gauntlet_clink" : "Gauntlet Clinks",
  "subtitles.bosses_of_mass_destruction.soul_star" : "灵魂之星坠落",

  "subtitles.bosses_of_mass_destruction.energy_shield" : "黑曜石护盾",
  "subtitles.bosses_of_mass_destruction.obsidilith_prepare_attack": "黑曜石蓄力",
  "subtitles.bosses_of_mass_destruction.spike" : "冰霜爆发",
  "subtitles.bosses_of_mass_destruction.spike_indicator" : "Frost Gathers",
  "subtitles.bosses_of_mass_destruction.wave_indicator":"集火",
  "subtitles.bosses_of_mass_destruction.obsidilith_burst":"能量爆发",
  "subtitles.bosses_of_mass_destruction.obsidilith_teleport" : "黑曜石传送",
  "subtitles.bosses_of_mass_destruction.obsidilith_death" : "黑曜石死了",
  "subtitles.bosses_of_mass_destruction.obsidilith_hurt" : "黑曜石伤害",
  "subtitles.bosses_of_mass_destruction.obsidilith_wave" : "大火爆发",

  "subtitles.bosses_of_mass_destruction.lich_death" : "巫妖之死",
  "subtitles.bosses_of_mass_destruction.lich_hurt" : "巫妖伤害",
  "subtitles.bosses_of_mass_destruction.lich_teleport" : "巫妖传送",
  "subtitles.bosses_of_mass_destruction.rage_prepare" : "巫妖狂暴",
  "subtitles.bosses_of_mass_destruction.minion_summon" : "幻影出现",
  "subtitles.bosses_of_mass_destruction.minion_rune" : "符文出现",
  "subtitles.bosses_of_mass_destruction.teleport_prepare" : "Lich 准备传送",
  "subtitles.bosses_of_mass_destruction.missile_prepare" : "巫妖准备冰球",
  "subtitles.bosses_of_mass_destruction.missile_shoot" : "巫妖射出冰球",
  "subtitles.bosses_of_mass_destruction.comet_prepare" : "Lich 准备彗星",
  "subtitles.bosses_of_mass_destruction.comet_shoot" : "巫妖发射彗星",
  "subtitles.bosses_of_mass_destruction.blue_fireball_land" : "冰球之地",

  "subtitles.bosses_of_mass_destruction.void_blossom_burrow":"开花洞穴",
  "subtitles.bosses_of_mass_destruction.void_blossom_spike":"尖峰",
  "subtitles.bosses_of_mass_destruction.spore_impact" : "毒药爆炸",
  "subtitles.bosses_of_mass_destruction.petal_blade":"花瓣",
  "subtitles.bosses_of_mass_destruction.spore_prepare" : "毒药冒泡",
  "subtitles.bosses_of_mass_destruction.spike_wave_indicator":"地颤",
  "subtitles.bosses_of_mass_destruction.spore_ball_land" : "毒地",
  "subtitles.bosses_of_mass_destruction.void_spike_indicator":"尖峰聚集",
  "subtitles.bosses_of_mass_destruction.void_blossom_hurt" : "花伤",
  "subtitles.bosses_of_mass_destruction.void_blossom_fall": "开花瀑布",
  "subtitles.bosses_of_mass_destruction.earthdive_spear_throw" : "长矛投掷",
  "subtitles.bosses_of_mass_destruction.charged_ender_pearl" : "珍珠大陆",
  "subtitles.bosses_of_mass_destruction.brimstone" : "硫磺释放",

  "text.autoconfig.bosses_of_mass_destruction.title" : "所有更改都需要重启 mc",

  "text.autoconfig.bosses_of_mass_destruction.category.Lich": "Lich",
  "text.autoconfig.bosses_of_mass_destruction.option.lichConfig.eternalNighttime" : "应用永恒之夜",
  "text.autoconfig.bosses_of_mass_destruction.option.lichConfig.experienceDrop" : "经验下降",
  "text.autoconfig.bosses_of_mass_destruction.option.lichConfig.idleHealingPerTick" : "每刻空闲治疗",
  "text.autoconfig.bosses_of_mass_destruction.option.lichConfig.health": "健康",
  "text.autoconfig.bosses_of_mass_destruction.option.lichConfig.missile": "导弹",
  "text.autoconfig.bosses_of_mass_destruction.option.lichConfig.missile.statusEffectId": "状态效果",
  "text.autoconfig.bosses_of_mass_destruction.option.lichConfig.missile.statusEffectDuration" : "状态效果持续时间",
  "text.autoconfig.bosses_of_mass_destruction.option.lichConfig.missile.statusEffectPotency": "状态效应效力",
  "text.autoconfig.bosses_of_mass_destruction.option.lichConfig.missile.damage": "伤害",
  "text.autoconfig.bosses_of_mass_destruction.option.lichConfig.comet": "彗星",
  "text.autoconfig.bosses_of_mass_destruction.option.lichConfig.comet.explosionStrength": "爆炸强度",
  "text.autoconfig.bosses_of_mass_destruction.option.lichConfig.comet.destroysBlocks" : "摧毁方块",
  "text.autoconfig.bosses_of_mass_destruction.option.lichConfig.summonMechanic" : "灵魂之星掉落",
  "text.autoconfig.bosses_of_mass_destruction.option.lichConfig.summonMechanic.isEnabled": "启用",
  "text.autoconfig.bosses_of_mass_destruction.option.lichConfig.summonMechanic.entitiesThatCountToSummonCounter" : "可以掉落的实体",
  "text.autoconfig.bosses_of_mass_destruction.option.lichConfig.summonMechanic.numEntitiesKilledToDropSoulStar" : "每颗灵魂之星击杀数",
  "text.autoconfig.bosses_of_mass_destruction.option.lichConfig.generateLichTower": "启用巫妖塔生成",

  "text.autoconfig.bosses_of_mass_destruction.category.Obsidilith": "Obsidilith",
  "text.autoconfig.bosses_of_mass_destruction.option.obsidilithConfig.health": "健康",
  "text.autoconfig.bosses_of_mass_destruction.option.obsidilithConfig.armor": "装甲",
  "text.autoconfig.bosses_of_mass_destruction.option.obsidilithConfig.attack": "攻击",
  "text.autoconfig.bosses_of_mass_destruction.option.obsidilithConfig.idleHealingPerTick" : "每刻空闲治疗",
  "text.autoconfig.bosses_of_mass_destruction.option.obsidilithConfig.experienceDrop" : "经验下降",
  "text.autoconfig.bosses_of_mass_destruction.option.obsidilithConfig.spawnPillarOnDeath" : "死亡时生成柱子",
  "text.autoconfig.bosses_of_mass_destruction.option.obsidilithConfig.anvilAttackExplosionStrength": "铁砧攻击爆炸强度",
  "text.autoconfig.bosses_of_mass_destruction.option.obsidilithConfig.arenaGeneration": "竞技场生成",
  "text.autoconfig.bosses_of_mass_destruction.option.obsidilithConfig.arenaGeneration.generationHeight": "世代高度",
  "text.autoconfig.bosses_of_mass_destruction.option.obsidilithConfig.arenaGeneration.generationSpacing": "世代间距",
  "text.autoconfig.bosses_of_mass_destruction.option.obsidilithConfig.arenaGeneration.generationSeparation": "世代分离",
  "text.autoconfig.bosses_of_mass_destruction.option.obsidilithConfig.arenaGeneration.generationEnabled" : "生成启用",

  "text.autoconfig.bosses_of_mass_destruction.category.Gauntlet": "Gauntlet",
  "text.autoconfig.bosses_of_mass_destruction.option.gauntletConfig.health": "健康",
  "text.autoconfig.bosses_of_mass_destruction.option.gauntletConfig.armor": "装甲",
  "text.autoconfig.bosses_of_mass_destruction.option.gauntletConfig.attack": "攻击",
  "text.autoconfig.bosses_of_mass_destruction.option.gauntletConfig.idleHealingPerTick" : "每刻空闲治疗",
  "text.autoconfig.bosses_of_mass_destruction.option.gauntletConfig.experienceDrop" : "经验下降",
  "text.autoconfig.bosses_of_mass_destruction.option.gauntletConfig.spawnAncientDebrisOnDeath" : "死亡时生成远古碎片",
  "text.autoconfig.bosses_of_mass_destruction.option.gauntletConfig.energizedPunchExplosionSize" : "充能拳爆炸强度",
  "text.autoconfig.bosses_of_mass_destruction.option.gauntletConfig.normalPunchExplosionMultiplier" : "普通打孔爆炸倍数",
  "text.autoconfig.bosses_of_mass_destruction.option.gauntletConfig.arenaGeneration" : "竞技场生成",
  "text.autoconfig.bosses_of_mass_destruction.option.gauntletConfig.arenaGeneration.generationSpacing": "世代间距",
  "text.autoconfig.bosses_of_mass_destruction.option.gauntletConfig.arenaGeneration.generationSeparation": "世代分离",
  "text.autoconfig.bosses_of_mass_destruction.option.gauntletConfig.arenaGeneration.generationEnabled" : "生成启用",

  "text.autoconfig.bosses_of_mass_destruction.category.VoidBlossom" : "虚空之花",
  "text.autoconfig.bosses_of_mass_destruction.option.voidBlossomConfig.health": "健康",
  "text.autoconfig.bosses_of_mass_destruction.option.voidBlossomConfig.armor": "装甲",
  "text.autoconfig.bosses_of_mass_destruction.option.voidBlossomConfig.attack": "攻击",
  "text.autoconfig.bosses_of_mass_destruction.option.voidBlossomConfig.idleHealingPerTick" : "每刻空闲治疗",
  "text.autoconfig.bosses_of_mass_destruction.option.voidBlossomConfig.experienceDrop" : "经验掉落",
  "text.autoconfig.bosses_of_mass_destruction.option.voidBlossomConfig.arenaGeneration" : "竞技场生成",
  "text.autoconfig.bosses_of_mass_destruction.option.voidBlossomConfig.arenaGeneration.generationSpacing": "世代间距",
  "text.autoconfig.bosses_of_mass_destruction.option.voidBlossomConfig.arenaGeneration.generationSeparation": "世代分离",
  "text.autoconfig.bosses_of_mass_destruction.option.voidBlossomConfig.arenaGeneration.generationEnabled": "生成启用"
}

**Comment by miyo6032** [comment]
Thanks!
