### ISSUE TITLE
I want to provide a traditional Chinese translation of this mod

### ISSUE THREAD

**Issue by oddcrafti** [miyo6032/bosses-of-mass-destruction#87]
I noticed someone else provided a translation for Simplified Chinese (zh_cn) 简体中文(中国大陆)
I want to refer to his content and translate it into traditional Chinese (zh_tw) 繁體中文(台灣)
--
{
"entity.bosses_of_mass_destruction.comet": "彗星",
"entity.bosses_of_mass_destruction.lich": "巫妖王",
"entity.bosses_of_mass_destruction.blue_fireball": "冰球咒",
"entity.bosses_of_mass_destruction.soul_star": "靈魂之星",
"entity.bosses_of_mass_destruction.obsidilith" : "黑曜石柱",
"entity.bosses_of_mass_destruction.gauntlet" : "地獄手套",
"entity.bosses_of_mass_destruction.void_blossom" : "虛空之花",
"entity.bosses_of_mass_destruction.spore_ball" : "孢子",
"entity.bosses_of_mass_destruction.petal_blade" : "花瓣之刃",

"block.bosses_of_mass_destruction.obsidilith_end_frame" : "黑曜石柱祭壇",
"block.bosses_of_mass_destruction.obsidilith_rune" : "黑曜石符文",
"block.bosses_of_mass_destruction.sealed_blackstone" : "密封黑石磚",
"block.bosses_of_mass_destruction.gauntlet_blackstone" : "遠古雕紋黑石",
"block.bosses_of_mass_destruction.chiseled_stone_altar" : "鑿石祭壇",
"block.bosses_of_mass_destruction.void_blossom_block" : "虛空之花生成點",
"block.bosses_of_mass_destruction.void_lily" : "虛空百合",
"block.bosses_of_mass_destruction.void_lily.tooltip" : "花粉被什麼東西吸引著",
"block.bosses_of_mass_destruction.void_blossom" : "虛空之花",
"block.bosses_of_mass_destruction.vine_wall" : "荊棘牆",

"itemGroup.bosses_of_mass_destruction.items" : "世界王",

"item.bosses_of_mass_destruction.soul_star" : "靈魂之星",
"item.bosses_of_mass_destruction.soul_star.tooltip" : "似乎指引我們到哪裡?",
"item.bosses_of_mass_destruction.ancient_anima" : "遠古心能",
"item.bosses_of_mass_destruction.blazing_eye" : "灼熱之眼",
"item.bosses_of_mass_destruction.obsidian_heart" : "黑曜石核心",
"item.bosses_of_mass_destruction.void_thorn" : "虛空荊棘",
"item.bosses_of_mass_destruction.crystal_fruit" : "水晶果實",
"item.bosses_of_mass_destruction.crystal_fruit.tooltip" : "提供短暫的回復II與抗性",
"item.bosses_of_mass_destruction.charged_ender_pearl" : "帶電終界珍珠",
"item.bosses_of_mass_destruction.charged_ender_pearl.tooltip" : "冷卻後可重複使用，並在傳送後",
'item.bosses_of_mass_destruction.charged_ender_pearl.tooltip2':'給予短暫抗性',
"item.bosses_of_mass_destruction.crafting_material.tooltip" : "製作素材",
"item.bosses_of_mass_destruction.brimstone_nectar" : "硫磺的花蜜",
"item.bosses_of_mass_destruction.brimstone_nectar.tooltip" : "使用時重置距離最近的世界王結構",

"block.bosses_of_mass_destruction.mob_ward" : "生命權杖",
"item.bosses_of_mass_destruction.mob_ward.tooltip" : "放置時，方圓64格方塊內不會生成任何生物",

"block.bosses_of_mass_destruction.monolith_block" : "毀滅增幅石碑",
"item.bosses_of_mass_destruction.monolith_block.tooltip_0" : "放置時增加一定範圍內的爆炸威力30%",
"item.bosses_of_mass_destruction.monolith_block.tooltip_1" : "方圓64格方塊內，此效果無法疊加",

"block.bosses_of_mass_destruction.levitation_block" : "懸浮魔方",
"item.bosses_of_mass_destruction.levitation_block.tooltip" : "放置時在7x7的有效範圍內允許創造飛行能力",

"item.bosses_of_mass_destruction.earthdive_spear.tooltip" : "蓄力滿可以穿越一定距離的實體方塊",
"item.bosses_of_mass_destruction.earthdive_spear" : "次元矛",

"advancements.nether.gauntlet_defeat.title": "握手言和...嗎?",
"advancements.nether.gauntlet_defeat.description" : "擊敗地獄手套",

"advancements.end.obsidilith_defeat.title": "最後的黑曜石",
"advancements.end.obsidilith_defeat.description" : "擊敗黑曜石柱",

"advancements.adventure.night_lich_defeat.title": "終結永夜，迎接黎明",
"advancements.adventure.night_lich_defeat.description": "擊敗巫妖王,

"advancements.adventure.void_blossom_defeat.title": "何必單戀一枝花",
"advancements.adventure.void_blossom_defeat.description": "擊敗虛空之花",

"subtitles.bosses_of_mass_destruction.gauntlet_idle" : "地獄手套呼吸",
"subtitles.bosses_of_mass_destruction.gauntlet_hurt" : "地獄手套攻擊",
"subtitles.bosses_of_mass_destruction.gauntlet_cast" : "地獄手套投擲",
"subtitles.bosses_of_mass_destruction.gauntlet_spin_punch" : "地獄手套旋轉",
"subtitles.bosses_of_mass_destruction.gauntlet_laser_charge" : "地獄手套蓄力",
"subtitles.bosses_of_mass_destruction.gauntlet_death" : "地獄手套死亡",
"subtitles.bosses_of_mass_destruction.gauntlet_clink" : "地獄手套叮噹",
"subtitles.bosses_of_mass_destruction.soul_star" : "靈魂之星掉落",

"subtitles.bosses_of_mass_destruction.energy_shield" : "黑曜石柱護盾",
"subtitles.bosses_of_mass_destruction.obsidilith_prepare_attack": "黑曜石柱蓄力",
"subtitles.bosses_of_mass_destruction.spike" : "冰霜爆發",
"subtitles.bosses_of_mass_destruction.spike_indicator" : "冰霜聚集",
"subtitles.bosses_of_mass_destruction.wave_indicator":"集火",
"subtitles.bosses_of_mass_destruction.obsidilith_burst":"能量爆發",
"subtitles.bosses_of_mass_destruction.obsidilith_teleport" : "黑曜石柱傳送",
"subtitles.bosses_of_mass_destruction.obsidilith_death" : "黑曜石柱死亡",
"subtitles.bosses_of_mass_destruction.obsidilith_hurt" : "黑曜石柱攻擊",
"subtitles.bosses_of_mass_destruction.obsidilith_wave" : "大火爆發",

"subtitles.bosses_of_mass_destruction.lich_death" : "巫妖王死亡",
"subtitles.bosses_of_mass_destruction.lich_hurt" : "巫妖王攻擊,
"subtitles.bosses_of_mass_destruction.lich_teleport" : "巫妖王傳送",
"subtitles.bosses_of_mass_destruction.rage_prepare" : "巫妖王狂暴",
"subtitles.bosses_of_mass_destruction.minion_summon" : "夜魅出現",
"subtitles.bosses_of_mass_destruction.minion_rune" : "符文出現",
"subtitles.bosses_of_mass_destruction.teleport_prepare" : "巫妖王準備傳送",
"subtitles.bosses_of_mass_destruction.missile_prepare" : "巫妖王準備冰球",
"subtitles.bosses_of_mass_destruction.missile_shoot" : "巫妖王發射冰球",
"subtitles.bosses_of_mass_destruction.comet_prepare" : "巫妖王準備彗星",
"subtitles.bosses_of_mass_destruction.comet_shoot" : "巫妖王發射彗星",
"subtitles.bosses_of_mass_destruction.blue_fireball_land" : "冰球咒",

"subtitles.bosses_of_mass_destruction.void_blossom_burrow":"花之巢穴",
"subtitles.bosses_of_mass_destruction.void_blossom_spike":"尖刺",
"subtitles.bosses_of_mass_destruction.spore_impact" : "毒藥爆炸",
"subtitles.bosses_of_mass_destruction.petal_blade":"花瓣",
"subtitles.bosses_of_mass_destruction.spore_prepare" : "毒藥冒泡",
"subtitles.bosses_of_mass_destruction.spike_wave_indicator":"地顫",
"subtitles.bosses_of_mass_destruction.spore_ball_land" : "毒液",
"subtitles.bosses_of_mass_destruction.void_spike_indicator":"尖刺聚集",
"subtitles.bosses_of_mass_destruction.void_blossom_hurt" : "開花傷害",
"subtitles.bosses_of_mass_destruction.void_blossom_fall": "開花粉塵",
"subtitles.bosses_of_mass_destruction.earthdive_spear_throw" : "長矛投擲",
"subtitles.bosses_of_mass_destruction.charged_ender_pearl" : "帶電終界珍珠",
"subtitles.bosses_of_mass_destruction.brimstone" : "硫磺釋放",

"text.autoconfig.bosses_of_mass_destruction.title" : "更改設置需要重新啟動遊戲才能套用",

"text.autoconfig.bosses_of_mass_destruction.category.Lich": "巫妖王",
"text.autoconfig.bosses_of_mass_destruction.option.lichConfig.eternalNighttime" : "應用永夜效果",
"text.autoconfig.bosses_of_mass_destruction.option.lichConfig.experienceDrop" : "經驗掉落",
"text.autoconfig.bosses_of_mass_destruction.option.lichConfig.idleHealingPerTick" : "每刻空閒治癒",
"text.autoconfig.bosses_of_mass_destruction.option.lichConfig.health": "生命值",
"text.autoconfig.bosses_of_mass_destruction.option.lichConfig.missile": 導彈",
"text.autoconfig.bosses_of_mass_destruction.option.lichConfig.missile.statusEffectId": "狀態效果",
"text.autoconfig.bosses_of_mass_destruction.option.lichConfig.missile.statusEffectDuration" : "狀態效果持續時間",
"text.autoconfig.bosses_of_mass_destruction.option.lichConfig.missile.statusEffectPotency": "狀態效應力",
"text.autoconfig.bosses_of_mass_destruction.option.lichConfig.missile.damage": "傷害",
"text.autoconfig.bosses_of_mass_destruction.option.lichConfig.comet": "彗星",
"text.autoconfig.bosses_of_mass_destruction.option.lichConfig.comet.explosionStrength": "爆炸強度",
"text.autoconfig.bosses_of_mass_destruction.option.lichConfig.comet.destroysBlocks" : "破壞方塊",
"text.autoconfig.bosses_of_mass_destruction.option.lichConfig.summonMechanic" : "靈魂之星掉落",
"text.autoconfig.bosses_of_mass_destruction.option.lichConfig.summonMechanic.isEnabled": "啟用",
"text.autoconfig.bosses_of_mass_destruction.option.lichConfig.summonMechanic.entitiesThatCountToSummonCounter" : "可以掉落的物品",
"text.autoconfig.bosses_of_mass_destruction.option.lichConfig.summonMechanic.numEntitiesKilledToDropSoulStar" : "靈魂之星掉落率",
"text.autoconfig.bosses_of_mass_destruction.option.lichConfig.generateLichTower": "啟用巫妖塔生成",

"text.autoconfig.bosses_of_mass_destruction.category.Obsidilith": "黑曜石柱",
"text.autoconfig.bosses_of_mass_destruction.option.obsidilithConfig.health": "生命值",
"text.autoconfig.bosses_of_mass_destruction.option.obsidilithConfig.armor": "護甲",
"text.autoconfig.bosses_of_mass_destruction.option.obsidilithConfig.attack": "攻擊",
"text.autoconfig.bosses_of_mass_destruction.option.obsidilithConfig.idleHealingPerTick" : "每刻空閒治癒",
"text.autoconfig.bosses_of_mass_destruction.option.obsidilithConfig.experienceDrop" : "經驗掉落",
"text.autoconfig.bosses_of_mass_destruction.option.obsidilithConfig.spawnPillarOnDeath" : "死亡時生成柱子",
"text.autoconfig.bosses_of_mass_destruction.option.obsidilithConfig.anvilAttackExplosionStrength": "石柱攻擊爆炸強度",
"text.autoconfig.bosses_of_mass_destruction.option.obsidilithConfig.arenaGeneration": "結構生成",
"text.autoconfig.bosses_of_mass_destruction.option.obsidilithConfig.arenaGeneration.generationHeight": "結構高度",
"text.autoconfig.bosses_of_mass_destruction.option.obsidilithConfig.arenaGeneration.generationSpacing": "結構間距",
"text.autoconfig.bosses_of_mass_destruction.option.obsidilithConfig.arenaGeneration.generationSeparation": "結構分離",
"text.autoconfig.bosses_of_mass_destruction.option.obsidilithConfig.arenaGeneration.generationEnabled" : "生成啟用",

"text.autoconfig.bosses_of_mass_destruction.category.Gauntlet": "地獄手套",
"text.autoconfig.bosses_of_mass_destruction.option.gauntletConfig.health": "生命值",
"text.autoconfig.bosses_of_mass_destruction.option.gauntletConfig.armor": "護甲",
"text.autoconfig.bosses_of_mass_destruction.option.gauntletConfig.attack": "攻擊",
"text.autoconfig.bosses_of_mass_destruction.option.gauntletConfig.idleHealingPerTick" : "每刻空閒治癒",
"text.autoconfig.bosses_of_mass_destruction.option.gauntletConfig.experienceDrop" : "經驗掉落",
"text.autoconfig.bosses_of_mass_destruction.option.gauntletConfig.spawnAncientDebrisOnDeath" : "死亡時生成遠古遺骸",
"text.autoconfig.bosses_of_mass_destruction.option.gauntletConfig.energizedPunchExplosionSize" : "蓄力拳爆炸強度",
"text.autoconfig.bosses_of_mass_destruction.option.gauntletConfig.normalPunchExplosionMultiplier" : "普通拳爆炸指數",
"text.autoconfig.bosses_of_mass_destruction.option.gauntletConfig.arenaGeneration" : "結構生成",
"text.autoconfig.bosses_of_mass_destruction.option.gauntletConfig.arenaGeneration.generationSpacing": "結構間距",
"text.autoconfig.bosses_of_mass_destruction.option.gauntletConfig.arenaGeneration.generationSeparation": "結構分離",
"text.autoconfig.bosses_of_mass_destruction.option.gauntletConfig.arenaGeneration.generationEnabled" : "生成啟用,

"text.autoconfig.bosses_of_mass_destruction.category.VoidBlossom" : "虛空之花",
"text.autoconfig.bosses_of_mass_destruction.option.voidBlossomConfig.health": "生命值",
"text.autoconfig.bosses_of_mass_destruction.option.voidBlossomConfig.armor": "護甲",
"text.autoconfig.bosses_of_mass_destruction.option.voidBlossomConfig.attack": "攻擊",
"text.autoconfig.bosses_of_mass_destruction.option.voidBlossomConfig.idleHealingPerTick" : "每刻空閒治癒",
"text.autoconfig.bosses_of_mass_destruction.option.voidBlossomConfig.experienceDrop" : "經驗掉落",
"text.autoconfig.bosses_of_mass_destruction.option.voidBlossomConfig.arenaGeneration" : "結構生成",
"text.autoconfig.bosses_of_mass_destruction.option.voidBlossomConfig.arenaGeneration.generationSpacing": "結構間距,
"text.autoconfig.bosses_of_mass_destruction.option.voidBlossomConfig.arenaGeneration.generationSeparation": "結構分離",
"text.autoconfig.bosses_of_mass_destruction.option.voidBlossomConfig.arenaGeneration.generationEnabled": "生成啟用"

**Comment by miyo6032** [comment]
Thanks!
