### ISSUE TITLE
Game crashes as soon as a boss is loaded

### ISSUE THREAD

**Issue by Voidner** [miyo6032/bosses-of-mass-destruction#89]
[crash-2022-12-17_17.34.08-client.txt](https://github.com/miyo6032/bosses-of-mass-destruction/files/10252165/crash-2022-12-17_17.34.08-client.txt)

**Comment by miyo6032** [comment]
Your geckolib version is pretty old try a newer version

**Comment by Voidner** [comment]
updating geckolib and bosses of mass destruction fixed it, idk which one had to be updated but it worked ty very much
