### ISSUE TITLE
Optional integration with Gravity api

### ISSUE THREAD

**Issue by Defetyre** [miyo6032/bosses-of-mass-destruction#90]
Make it so that if you have Gravity api installed, the Nether Gauntlet will gain an ability to switch player's gravity in any direction while doing a "pointing" animation.
I know that it's probably an obscure suggestion you have no time for, but I think that it can significantly enhance the battle for a relatively small effort because all it takes is to make one new animation and a small tweak in its AI to utilize the library.
The mechanic of gravity altering will synergize perfectly with all the other attacks of this boss as well as its arena, but I mostly though about how cool and dynamic the fight would feel if the gravity changing ability could be accompanied by something like a pointing animation

**Comment by miyo6032** [comment]
it is a cool suggestion but i am unfortunately only doing minimal support issues for this mod now
