### ISSUE TITLE
Enchancement Frostbite enchantment interrupts/breaks boss death animation

### ISSUE THREAD

**Issue by Shunigate1** [miyo6032/bosses-of-mass-destruction#98]
When using a weapon enchanted with Frostbite from the mod "Enchancement" to kill a boss (specifically the Nether Gauntlet is what I tested this on), the boss will turn into an ice sculpture as expected from the enchantment, but its death animation will no longer play, resulting in nothing being dropped.

**Comment by FumpleWumper** [comment]
I opened this as an issue in the Enchancement page and apparently it's because the bosses in this mod aren't properly tagged as bosses.
If they get properly tagged it will fix this issue because Frostbite by default doesn't work on entities tagged as bosses

**Comment by miyo6032** [comment]
This should be fixed in 1.7.3
